name: Auto Changelog

on:
  push:
    branches:
      - master
      - prueba-changelog

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Determine version
        id: version
        run: |
          TAG_COUNT=$(git tag | wc -l)
          if [ "$TAG_COUNT" -eq "0" ]; then
            echo "first_release=3.0.0" >> $GITHUB_OUTPUT
          else
            echo "first_release=" >> $GITHUB_OUTPUT
          fi

      - name: Generate changelog
        run: |
          if [ -n "${{ steps.version.outputs.first_release }}" ]; then
            echo "No tags found. Forcing version 3.0.0"
            standard-version --release-as ${{ steps.version.outputs.first_release }}
          else
            standard-version
          fi

      - name: Push changes
        run: |
          git push --follow-tags origin HEAD
